core:
  type: dict
  schema:
    affinity:
      type: string
      default: ''
    api_jobno:
      type: string
    artifacts_base_dir:
      type: string
      default: ./logs
    artifacts_dir:
      type: string
      nullable: true
      default: null
    exitcode:
      type: integer
    flush_config_to:
      type: string
    ignore_locks:
      type: boolean
    uuid:
      type: string
    pid:
      type: integer
    message:
      type: string
    lock_dir:
      type: string
      default: /var/lock/
    operator:
      type: string
    taskset_path:
      type: string
      default: taskset
version:
  type: string