core:
  lock_dir: /var/lock
  artifacts_base_dir: logs
phantom:
  package: yandextank.plugins.Phantom
  enabled: true
  address: load.wfront.yandex.net
  load_profile:
    load_type: rps
    schedule: step(50,900,5,5)
  instances: 1000
  header_http: '1.1'
  threads: 17
  tank_type: http
  ammo_type: phantom
  use_caching: true
  file_cache: 8192
  force_stepping: 0
  loop: -1
  ammo_limit: -1
  enum_ammo: false
  connection_test: false
  uris: /
aggregator:
  package: yandextank.plugins.Aggregator
  enabled: true
  precise_cumulative: 0
  time_periods: 1ms 2 3 4 5 6 7 8 9 10 20 30 40 50 60 70 80 90 100 150 200 250 300 350 400 450 500 600 650 700 750 800 850 900 950 1s 1500 2s 2500 3s 3500 4s 4500 5s 5500 6s 6500 7s 7500 8s 8500 9s 9500 10s 11s
meta:
  package: yandextank.plugins.DataUploader
  enabled: true
  api_address: https://lunapark.yandex-team.ru/
  task: LOAD-204
  operator: fomars
  job_name: "[1495714217] [api_v2] portal-morda-conf=2017.05.25-0"
  lock_targets: auto
telegraf:
  package: yandextank.plugins.Telegraf
  enabled: true
  config: monitoring1.xml
  default_target: localhost
  ssh_timeout: 5s
autostop:
  package: yandextank.plugins.Autostop
  enabled: true